[workspace]
members = [
    "blackjack-core",
    "blackjack-cli",
    "blackjack-gui",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
blackjack-core = { path = "/blackjack-core" }
